# Generated by Django 2.0.3 on 2018-03-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='firstruc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.CharField(max_length=250)),
                ('pnr', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=10000)),
                ('complaint', models.CharField(max_length=10000)),
                ('description', models.CharField(max_length=10000)),
                ('tripstatus', models.BooleanField()),
                ('location', models.CharField(max_length=70)),
            ],
        ),
    ]
