# Generated by Django 2.0.3 on 2018-03-26 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fir', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firstruc',
            name='tripstatus',
        ),
    ]
