# Generated by Django 2.0.3 on 2018-03-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pnr',
        ),
    ]
